dgraph-io/charts

README.md
charts/dgraph/Chart.yaml
charts/dgraph/README.md
charts/dgraph/values.yaml

- Hard-coding the Dgraph version to the latest release (v1.2.1)
- Moving top-level README file to dgraph chart folder and minor changes
- Adding short top-level README
Signed-off-by: Prashant Shahi <prashant@dgraph.io>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/8)

Hard-coding the Dgraph version and Updating Helm chart docs

---

charts/dgraph/templates/alpha-statefulset.yaml
charts/dgraph/templates/ratel-deployment.yaml
charts/dgraph/templates/zero-statefulset.yaml
charts/dgraph/values.yaml

Adding support for user specified environment variables for zero, alpha, ratel.
* Add extraEnvs option in values.yaml under ratel, zero, and alpha
* Update documentation links
Example of ysing this in `values.yaml`
```yaml
alpha
extraEnvs:
- name: AWS_ACCESS_KEY_ID
value: "XXXXXXXXXXXXXXXXXXXX"
- name: AWS_SECRET_ACCESS_KEY
value: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
```
You can test out the values before deploying with:
```bash
git clone git@github.com:dgraph-io/charts.git
helm install --dry-run --debug --generate-name charts/charts/dgraph/
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/22)

DGRAPH-1564 User Specified Ports for Zero, Alpha, Ratel

---

charts/dgraph/templates/alpha-svc.yaml
charts/dgraph/templates/ratel-svc.yaml
charts/dgraph/templates/zero-svc.yaml
charts/dgraph/values.yaml

This adds support for user specified annotations.  This is required for features like:
* TLS certificate termination with AWS ELB
* ExternalDNS registration, e.g. AWS Route53, GoogleCloud CloudDNS
* Service Meshes, e.g. Itsio, Linkerd
* Configure LoadBalancer to be internal private network only
Testing:
1. Testing without `alpha.service.annotations` key
2. Testing default with `alpha.service.annotations` with empty set `{}`
3. Testing with annotation value set, e.g.
```bash
helm install debug --debug --dry-run ./charts/charts/dgraph/ -f values.yaml
```
```yaml
alpha:
name: alpha
service:
type: LoadBalancer
annotations:
service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Support for Service Annotations

---

charts/dgraph/templates/ratel-deployment.yaml
charts/dgraph/templates/ratel-svc.yaml
charts/dgraph/values.yaml

Added functionality to disable installing ratel (default is enabled).  Setting `ratel.enabled` to `false` will disable the service and deployment.
Service also changed to `80` from `8000`.  Backend port from  docker container is still port `8000`.
```bash
$ helm install dgraph-ratel-enabled ./charts/charts/dgraph/ --set ratel.enabled=true
$ kubectl get deployment | grep dgraph-ratel-enabled
dgraph-ratel-enabled-dgr-ratel                           1/1     1            1           75s
$ kubectl get svc | grep dgraph-ratel-enabled
dgraph-ratel-enabled-dgr-alpha                      ClusterIP      10.100.234.218   <none>                                                                    8080/TCP,9080/TCP               56s
dgraph-ratel-enabled-dgr-alpha-headless             ClusterIP      None …
```

ratel update to optional disable ratel

---

charts/dgraph/Chart.yaml
charts/dgraph/templates/global-ingress.yaml
charts/dgraph/templates/ratel-ingress.yaml

Ingress needs to be updated to support recent Ratel update.  Specifically:
* ingress needs to use servicePort 80, not 8000 as ratel port was changed
* ingress for ratel service need be disabled if ratel is not enabled
Also
* version bump helm chart
This was tested with four helm chart values using:
```bash
helm install test --debug --dry-run ./charts/charts/dgraph/ -f my_values.yaml
```
```yaml
ratel:
enabled: false
ingress:
enabled: true
hostname: ratel.example.com
annotations:
kubernetes.io/ingress.class: alb
alb.ingress.kubernetes.io/target-type: ip
alb.ingress.kubernetes.io/scheme: internet-facing
alpha:
ingress:
enabled: true
hostname: alpha.example.com
annotations:
kubernetes.io/ingress.class: alb
alb.ingress.kubernetes.io/target-type: ip
alb.ingress.kubernetes.io/scheme: …
```

Ingress Update Fix for Ratel Compatibility

---

charts/dgraph/Chart.yaml
charts/dgraph/templates/alpha-svc.yaml
charts/dgraph/templates/zero-svc.yaml
charts/dgraph/values.yaml

The `publishNotReadyAddresses` for a service resource is an immutable static value in the template, which will prevent a cluster from becoming ready in alternative orchestration patterns, such as using Itsio.  This allows user to change the value should the need arise.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/34)

Service publishNotReadyAddresses value is now configurable

---

charts/dgraph/Chart.yaml
charts/dgraph/templates/alpha-statefulset.yaml
charts/dgraph/templates/ratel-deployment.yaml
charts/dgraph/templates/zero-statefulset.yaml
charts/dgraph/values.yaml

Fixes:
* fix alpha `readinessProbe` - was using `livenessProbe` check
* fix zero `readinessProbe` - was using `livenessProbe` check
* fix ratel `readinessProbe` - was using `livenessProbe` check
* update `values.yaml` to use `/health` for zero `readinessProbe`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/32)

Bug Fixes for readinessProbe

---

charts/dgraph/Chart.yaml
charts/dgraph/templates/alpha-statefulset.yaml
charts/dgraph/templates/ratel-deployment.yaml
charts/dgraph/templates/zero-statefulset.yaml
charts/dgraph/values.yaml

The current health probes (liveness and readiness) only support http.  A customized health, such as cmd.exec, is needed mTLS and service meshes like Itsio.
This solution will allow an alternative custom health probes for alpha, zero, ratel.
Tested the following:
* rendering using existing `livenessProbe` and `readinessProbe` (regression)
* rendering using new `customLivenessProbe` and `customReadinessProbe`
* deployed custom version on GKE
Example:
```yaml
ratel:
customLivenessProbe:
httpGet:
port: 8000
path: /
initialDelaySeconds: 30
periodSeconds: 10
timeoutSeconds: 5
successThreshold: 1
failureThreshold: 6
customReadinessProbe:
httpGet:
port: 8000
path: /
initialDelaySeconds: 5
periodSeconds: 10
timeoutSeconds: 5
successThreshold: 1
failureThreshold: 6
service:
type: NodePort
ingress: …
```

custom liveness/readiness probe

---

charts/dgraph/Chart.yaml
charts/dgraph/templates/alpha-statefulset.yaml

This adds the ability to create a comma separated list of multiple zeros for support dgraph versions for https://github.com/dgraph-io/dgraph/pull/5116/
This is forward and backwards compatible (thanks to Go template Sprig library)
* versions less than v1.2.3 will have single `dgraph-zero.0` item for `alpha --zero` option
* versions equal or greater than v1.2.3 will have multiple zeros, e.g. `dgraph-zero.0`, `dgraph-zero.1`, `dgraph-zero.2`, up to number of `zero.replicaCount` specified by user
Types of tests:
* **Test**: `helm install dgraph-test charts/charts/dgraph`
**Result**: `dgraph alpha --zero` will have 3 zeros
* **Test** `helm install dgraph-test charts/charts/dgraph --set zero.replicaCount=5`
**Result**: `dgraph alpha --zero` will have 5 zeros
* **Test** `helm install …

Alpha multi zero support

---

charts/dgraph/Chart.yaml
charts/dgraph/README.md
charts/dgraph/templates/alpha-statefulset.yaml
charts/dgraph/templates/zero-statefulset.yaml
charts/dgraph/values.yaml

This adds an optional `startupProbe` that works with Kubernetes v1.16+.  It will break on default versions of Kubernetes on Amazon EKS, GKE platforms.
You can test this out before deploying with: 
```bash
helm install dgraph-test \
--set alpha.startupProbe.enabled=true \
--set zero.startupProbe.enabled=true \
--set alpha.livenessProbe.enabled=true \
--set zero.livenessProbe.enabled=true \
--set alpha.readinessProbe.enabled=true \
--set zero.readinessProbe.enabled=true \
--debug \
--dry-run \
charts/charts/dgraph/
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/39)

startupProbe

---

charts/dgraph/templates/alpha-statefulset.yaml

The support for multi-zero `dgraph alpha` setting broke support for `image.tag` set to `master` or `latest`.  This fixes that issue.
```bash
TEST_MULTIZERO="v1.2.3 v20.03.1 latest master"
for TESTVER in $TEST_MULTIZERO; do 
helm install tag-test \
--set image.tag=$TESTVER \
--dry-run \
--debug \
charts/charts/dgraph/ 2> /dev/null | grep 'dgraph alpha'
done
TEST_SINGLEZERO="v1.2.2 v20.03.0"
for TESTVER in $TEST_MULTIZERO; do 
helm install tag-test \
--set image.tag=$TESTVER \
--dry-run \
--debug \
charts/charts/dgraph/ 2> /dev/null | grep 'dgraph alpha'
done
```
Fixes https://discuss.dgraph.io/t/helm-chart-0-0-7-fails-when-image-tag-set-to-latest/8878
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

fix for image.tag of latest or master will work with multi-zero support

---

charts/dgraph/templates/global-ingress.yaml

Ratel ingress should go to the Ratel service (not Alpha service).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/44)

fix(ingress): Fix serviceName backend for Ratel ingress.

---

charts/dgraph/README.md
charts/dgraph/example_values/backup-volume-config.yaml
charts/dgraph/templates/alpha/statefulset.yaml
charts/dgraph/templates/backups/cronjob-full.yaml
charts/dgraph/templates/backups/cronjob-inc.yaml
charts/dgraph/values.yaml

This adds support for general volumes that can be mounted in Alpha pods, such as EdgeFS, Cassandra, CephFS with Rook (https://rook.io/).  The customer must configure PV + PVC (with ReadWriteMany access mode so that one volume can be mounted under several pods).
TL;DR If a default storage class is available, you can use this:
Default Storage Class is helpful (default config in EKS, AKS, GKE):
```bash
cat <<-EOF > pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
name: my-backups-claim
spec:
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 32Gi
EOF
kubectl apply -f pvc.yaml
CHART_PATH=path/to/charts/charts/dgraph
helm install test \
--namespace default $CHART_PATH \
--values $CHART_PATH/example_values/backup-volume-config.yaml \
--set …
```

Backup Support for Volumes

---

charts/dgraph/Chart.yaml
charts/dgraph/README.md
charts/dgraph/templates/_helpers.tpl
charts/dgraph/templates/alpha/statefulset.yaml
charts/dgraph/values.yaml

This adds a generic init container for the helm chart where operators can do some pre-cluster operations, such as _offline restore_ or _bulk loader_ before the alpha group starts up.  
The operator can use this for anything type of script they chose, or default and run ad-hoc commands and then `touch /dgraph/doneinit` once completed.
This is forward compatible with future restore initContainer and bulkloader initContainer, which will be added later.
```bash
helm install t1 --set alpha.initContainers.generic.enabled=false charts/dgraph/
helm delete t1 && kubectl delete pvc -l release=t1
helm install t2 --set alpha.initContainers.generic.enabled=true charts/dgraph/
kubectl exec -ti t2-dgraph-alpha-0 -c t2-dgraph-alpha-init-generic -- touch doneinit
kubectl exec -ti t2-dgraph-alpha-1 -c …
```

feature: generic initContainer (SUCCESS-57)

---

charts/dgraph/scripts/get_alpha_list.sh
charts/dgraph/templates/alpha/statefulset.yaml
charts/dgraph/templates/backups/cronjob-full.yaml
charts/dgraph/templates/backups/cronjob-inc.yaml
charts/dgraph/templates/zero/statefulset.yaml

This removes references to the FQDN with domain name of **`cluster.local`**, for example: 
* BEFORE: **`myrelease-dgraph-zero-0.myrelease-dgraph-zero-headless.default.svc.cluster.local`**
* AFTER: **`myrelease-dgraph-zero-0.myrelease-dgraph-zero-headless.default.svc`**
This fixes a few scenarios:
* Local clusters, such as [microk8s](https://microk8s.io/), where a domain name is not used.
* Alternative internal DNS schemes where default **`cluster.local`** is not use
* https://discuss.dgraph.io/t/helm-chart-defaults-to-cluster-local/8269/3
This works because the resolver should always have **`cluster.lcoal`** or equivalent alternative domain name.  For example, on GKE, these search domains will be configured:
* **`default.svc.cluster.local`**
* **`svc.cluster.local`** 
* …

fix: remove using fqdn with `.cluster.local`

---

charts/dgraph/README.md
charts/dgraph/templates/alpha/statefulset.yaml
charts/dgraph/templates/zero/statefulset.yaml
charts/dgraph/values.yaml

This adds `extraFlags` option for customers to allow them to add additional command-line flags.
```
helm install test4 --set zero.extraFlags='--v=3 --trace=0.1' --set alpha.extraFlags='--v=3 --trace=0.1'  charts/dgraph/ 
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/51)

Feature: Extra Flags (SUCCESS-136)

---

charts/dgraph/README.md
charts/dgraph/templates/alpha/svc.yaml
charts/dgraph/templates/ratel/svc.yaml
charts/dgraph/templates/zero/svc.yaml
charts/dgraph/values.yaml

Support for these properties in Ratel, Alpha, Zero:
* `loadBalancerIP`
* `externalTrafficPolicy`
* `loadBalancerSourceRanges`
Testing:
```bash
helm install test --dry-run --debug --values values.yaml ~/charts/charts/dgraph/
```
```yaml
alpha:
service:
loadBalancerIP: 40.121.183.53
externalTrafficPolicy: Local
loadBalancerSourceRanges:
- "143.232.0.0/16"
zero:
service:
type: LoadBalancer
loadBalancerIP: 40.121.183.52
externalTrafficPolicy: Local
loadBalancerSourceRanges:
- "143.231.0.0/16"
ratel:
service:
loadBalancerIP: 40.121.183.54
externalTrafficPolicy: Cluster
loadBalancerSourceRanges:
- "143.233.0.0/16"
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/52)

SUCCESS-137 service loadbalancer support

---

charts/dgraph/README.md
charts/dgraph/templates/backups/cronjob-full.yaml
charts/dgraph/templates/backups/cronjob-inc.yaml
charts/dgraph/values.yaml

Currently the default restartPolicy for backup jobs is OnFailure.  This means it will continiously retry until success.  If for some reason the job will always fail, e.g. enterprise license has expired, then the job will both never fail and never succeed.  This makes it difficult to debug.
This change makes the job fail when it fails, as is consistent with typical cron use cases.  The operator will see something like:
```
dev-dgraph-backups-full-1607721900-726gm   0/1     Completed   0          16m
dev-dgraph-backups-full-1607722200-qj62g   0/1     Completed   0          11m
dev-dgraph-backups-full-1607722500-6p54h   0/1     Completed   0          6m8s
dev-dgraph-backups-full-1607722800-5blxs   0/1     Error       0          55s
dev-dgraph-backups-full-1607722800-8bbp5   0/1     Error …
```

Fix: Change default restartPolicy to Never

---

charts/dgraph/templates/backups/cronjob-full.yaml
charts/dgraph/templates/backups/cronjob-inc.yaml

This updates Kubernetes CronJobs to add new metadata that is useful for monitoring.  This will create a label of `cronjob` for the Kubernetes Job and corresponding Kubernetes Pod with the value that matches the Kubernetes CronJob metadata name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/56)

metadata labels utilized for backup monitoring

---

charts/dgraph/templates/_helpers.tpl

It happens when running a Jenkins X command `jx step helm build` which will run `helm lint --set tags.jx-lint=true --set global.jxLint=true --set-string global.jxTypeEnv=lint --values values.yaml`
```
==> Linting .
[ERROR] templates/: parse error in "env/charts/dgraph2/templates/_helpers.tpl": template: env/charts/dgraph2/templates/_helpers.tpl:73: illegal number syntax: "-"
```
```
==> Linting .
[ERROR] templates/: parse error in "env/charts/dgraph2/templates/_helpers.tpl": template: env/charts/dgraph2/templates/_helpers.tpl:91: illegal number syntax: "-"
```
```
~:> jx version
Version        2.1.114
Commit         e2198a9
Build date     2020-07-23T15:20:47Z
Go version     1.13.8
Git tree state clean
```
```
~:> helm version --client
Client: &version.Version{SemVer:"v2.17.0", …
```

Fixes parse errors when linting

---

charts/dgraph/templates/alpha/statefulset.yaml
charts/dgraph/templates/backups/cronjob-full.yaml
charts/dgraph/templates/backups/cronjob-inc.yaml
charts/dgraph/templates/ratel/deployment.yaml
charts/dgraph/templates/zero/statefulset.yaml
charts/dgraph/values.yaml

For people having their own storage solution (i.e. portworx) for on-premise kubernetes cluster like us, we need to be able to specify a scheduler name in order to use the dedicated storage nodes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/53)

add schedulerName option

---

PUBLISH.md

Fix typo for `helm lint` command.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/61)

docs: Fix typo in PUBLISH docs.

---

charts/dgraph/templates/alpha/statefulset.yaml
charts/dgraph/templates/zero/statefulset.yaml

The helm installation fails when persistence is disabled. e.g., setting either
alpha.persistence.enabled or zero.persistence.enabled to false.
$ helm install dev dgraph/dgraph --set alpha.persistence.enabled=false,zero.persistence.enabled=false
Error: YAML parse error on dgraph/templates/alpha/statefulset.yaml: error converting YAML to JSON: yaml: line 88: did not find expected key
The cause for this error can be seen when rendering the template. The emptyDir
config gets mangled with the configMap:
- name: config-volume
configMap:
name: dev-dgraph-alpha-config
- name: datadir
emptyDir: {}
Error: YAML parse error on dgraph/templates/alpha/statefulset.yaml: error converting YAML to JSON: yaml: line 88: did not find expected key
helm.go:81: [debug] error converting YAML to JSON: yaml: line …

fix: Configure no-persistence emptyDir correctly.

---

charts/dgraph/Chart.yaml
charts/dgraph/README.md
charts/dgraph/values.yaml

This updates dgraph image tag form `v20.11.1` to `v20.11.3`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/63)

feature(dgraph) version bump to dgraph v20.11.3

---

charts/dgraph/templates/backups/secrets.yaml

Fix issue where helm chart would fail if secret value was not of type string.  This affects:
* `backup_admin_password` - password for groot
* `backup_auth_token` - poor man's auth token for non-enterprise
* `s3_access_key` + `s3_secret_key` - AWS IAM credentials
* `minio_access_key` + `minio_secret_key` - MinIO credentials
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/62)

fix(dgraph) - fix backup secrets where some values can cause saving secret to fail

---

charts/dgraph/templates/zero/statefulset.yaml

This updates the new superflag format for the raft index.  Both earlier versions with `--idx <num>` and future version with `--raft idx=<num> are support.
Other dgraph flags/superflags are at user discretion through `zero.extraEnvs`, `zero.extraFlags`, `zero.configFile`, `alpha.extraEnvs`, `alpha.extraFlags`, or `alpha.configFile`, and so no changes needed for this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/64)

feature(dgraph) - forward support for v21.03 raft index superflag option

---

charts/dgraph/Chart.yaml
charts/dgraph/README.md
charts/dgraph/values.yaml

This update contains the following:
* update ratel image to now use dgraph/ratel, as ratel is no longer support in dgraph/dgraph image.
* version bump dgraph/dgraph image to v21.03.1 
* chart version upgrade for future release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/69)

fix: update image tag to dgraph/dgraph:v21.03.1 and dgraph/ratel:v21.03.0

---

charts/dgraph/example_values/ingress-nginx.yaml

Super small change: `enabled` needs to be `true`, because well, it's a example to get ingress to work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/67)

Update helm ingress example

---

charts/dgraph/README.md

There was a missing "configFile" entry for adding configuration options to alpha and zero.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/72)

Added "configFile" entry

---

charts/dgraph/Chart.yaml
charts/dgraph/example_values/ingress/ingress-nginx-grpc.yaml
charts/dgraph/example_values/ingress/ingress-nginx.yaml
charts/dgraph/templates/alpha/ingress.yaml
charts/dgraph/templates/global-ingress.yaml
charts/dgraph/templates/ratel/ingress.yaml
charts/dgraph/values.yaml

Ingress class is now a field instead of an annotation. Helm chart is still backwards compatible with older version by just leaving out `ingressClassName`, and leaving in the annotation.
Also, could you please release a new version of the charts? Because the currently published version is pretty old (dgraph v21.03.1)... We could really use this fixed version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/73)

Fix ingress for K8s v1.18

---

charts/dgraph/templates/ratel/ingress.yaml

Fix template typo with Ratel ingress introduced in #73.
$ helm lint charts/dgraph
==> Linting charts/dgraph
[ERROR] templates/: parse error at (dgraph/templates/ratel/ingress.yaml:49): unexpected {{end}}
Error: 1 chart(s) linted, 1 chart(s) failed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/74)

chore: Fix typo.

---

charts/dgraph/example_values/ingress/ingress-gce.yaml
charts/dgraph/example_values/ingress/ingress-nginx-grpc.yaml
charts/dgraph/example_values/ingress/ingress-nginx.yaml
charts/dgraph/example_values/ingress/kubernetes-ingress.yaml
charts/dgraph/values.yaml

The example for ingress-nginx for mixed grpc + https was technically functional, but not correct.  
* updated so that only proper certificates are generated via cert-manager.   
* added kubernetes-ingress for NGINX Ingress Controller example
* updated default value of  `ingressClassName` to  `null`
* minor comment corrections
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/77)

updated ingress examples and default value

---

charts/dgraph/README.md
charts/dgraph/templates/alpha/statefulset.yaml
charts/dgraph/templates/backups/cronjob-full.yaml
charts/dgraph/templates/backups/cronjob-inc.yaml
charts/dgraph/templates/ratel/deployment.yaml
charts/dgraph/templates/serviceaccount.yaml
charts/dgraph/templates/zero/statefulset.yaml
charts/dgraph/values.yaml

**problem**: Dgraph needs to run pods under the context of a service account, so that they can use security features.  For example:
* Access to cloud resources: [GKE Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity), [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html), [Azure AD Workload Identity](https://azure.github.io/azure-workload-identity/docs/), [Azure AD Pod Identity](https://github.com/Azure/aad-pod-identity)
* [SMI Traffic Access](https://github.com/servicemeshinterface/smi-spec/blob/main/apis/traffic-access/v1alpha2/traffic-access.md) control to restrict flow of traffic in a service mesh
**solution**: Add support for service accounts
**testing**:
**HOW TO TEST** You need to have a K8S running …

[dgraph] add support for service accounts

---

.gitignore
charts/dgraph/Chart.yaml
charts/dgraph/README.md
charts/dgraph/templates/alpha/statefulset.yaml
charts/dgraph/templates/backups/cronjob-full.yaml
charts/dgraph/templates/backups/cronjob-inc.yaml
charts/dgraph/templates/ratel/deployment.yaml
charts/dgraph/templates/zero/statefulset.yaml
charts/dgraph/values.yaml

The motivation for this PR was running dgraph on k8s cluster with Istio. The sidecar injection can be controlled by labeling the namespace or the pods. In this case:
- if the sidecar injection is enabled on namespace level - backup will never end since the pod will never finish (sidecar will run forever) and no option to disable it for backup pods
- no option to enable it for alpha/zero pods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/75)

Add extra pod labels

---

charts/dgraph/templates/ratel/deployment.yaml
charts/dgraph/values.yaml

Need an ability to override default ratel args. Unfortunately ratel doesn't grab these args from env variables, so helm `ratel.extraEnvs` variable is useless.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/81)

override default ratel args

---

charts/dgraph/Chart.yaml
charts/dgraph/README.md
charts/dgraph/values.yaml

This updates Dgraph version to `v22.0.2` and documents Ratel args override feature.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/83)

update version and document Ratel arg feature

---

charts/ratel/example_values/ingress/ingress-alb-no_host.yaml
charts/ratel/example_values/ingress/ingress-alb-with_host.yaml
charts/ratel/templates/ingress.yaml

This fixes #98
Fix can be verified the following below.  An absent `host:` key means this works. 
```shell
helm template --namespace ratel --create-namespace ./charts/ratel/ --values - <<EOF
ingress:
enabled: true
className: alb
annotations:
alb.ingress.kubernetes.io/scheme: internet-facing
alb.ingress.kubernetes.io/target-type: ip
hosts:
- paths:
- path: /*
pathType: ImplementationSpecific
EOF
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/99)

ratel ingress update

---

charts/dgraph/Chart.yaml
charts/dgraph/README.md
charts/dgraph/example_values/service_account.yaml
charts/dgraph/templates/alpha/statefulset.yaml
charts/dgraph/templates/ratel/deployment.yaml
charts/dgraph/templates/serviceaccount.yaml
charts/dgraph/templates/zero/statefulset.yaml
charts/dgraph/values.yaml

This adds feature to toggle whether or not to mount service account token credentials for the service.  This can be implemented in the following places:
* serviceAccount.automountServiceAccountToken - default for all services
* alpha.automountServiceAccountToken - toggle for just alpha
* zero.automountServiceAccountToken - toggle for just zero
* ratel.automountServiceAccountToken - toggle for just ratel http host
There's an example to turn it off except for alpha at:
* example_files/service_account.yaml
This can be tested with:
```bash
helm template ./charts/dgraph \
--values ./charts/dgraph/example_values/service_account.yaml
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

service account credential mount

---

charts/dgraph/README.md
charts/dgraph/templates/NOTES.txt
charts/dgraph/templates/_helpers.tpl
charts/dgraph/templates/alpha/configs.yaml
charts/dgraph/templates/alpha/ingress.yaml
charts/dgraph/templates/alpha/secret-acl.yaml
charts/dgraph/templates/alpha/secret-enc.yaml
charts/dgraph/templates/alpha/secret-tls.yaml
charts/dgraph/templates/alpha/statefulset.yaml
charts/dgraph/templates/alpha/svc-headless.yaml
charts/dgraph/templates/alpha/svc.yaml
charts/dgraph/templates/backups/configs.yaml
charts/dgraph/templates/backups/cronjob-full.yaml
charts/dgraph/templates/backups/cronjob-inc.yaml
charts/dgraph/templates/backups/pv.yaml
charts/dgraph/templates/backups/pvc.yaml
charts/dgraph/templates/backups/secrets.yaml
charts/dgraph/templates/global-ingress.yaml
charts/dgraph/templates/ratel/deployment.yaml
charts/dgraph/templates/ratel/ingress.yaml
charts/dgraph/templates/ratel/svc.yaml
charts/dgraph/templates/serviceaccount.yaml
charts/dgraph/templates/zero/configs.yaml
charts/dgraph/templates/zero/secret-tls.yaml
charts/dgraph/templates/zero/statefulset.yaml
charts/dgraph/templates/zero/svc-headless.yaml
charts/dgraph/templates/zero/svc.yaml

Adds possibility to deploy resources in the namespace different from the release one, useful in scenarios with umbrella helm charts.

[dgraph] feat: allow namespace override

---

charts/ratel/README.md
charts/ratel/templates/NOTES.txt
charts/ratel/templates/_helpers.tpl
charts/ratel/templates/deployment.yaml
charts/ratel/templates/ingress.yaml
charts/ratel/templates/service.yaml
charts/ratel/templates/serviceaccount.yaml
charts/ratel/templates/tests/test-connection.yaml

Adds possibility to deploy resources in the namespace different from the release one, useful in scenarios with umbrella helm charts.

[ratel] feat: allow namespace override

---

charts/dgraph/Chart.yaml
charts/dgraph/README.md
charts/dgraph/values.yaml
charts/ratel/Chart.yaml

- Minor version bump for dgraph and ratel, as we are introducing a backward compatible API.
- Bump default dgraph version to v23.1.0

bump dgraph and ratel chart versions

---

charts/dgraph/Chart.yaml
charts/dgraph/README.md
charts/dgraph/values.yaml

Updating dgraph chart versions to use 24.0.2
- Version bump for dgraph chart , aligning it with the application version 
-  Bump default dgraph version to v24.0.2

Updating Dgraph Charts to 24.0.2

---

charts/dgraph/Chart.yaml
charts/dgraph/README.md
charts/dgraph/values.yaml

Updating dgraph chart versions to use 24.0.4

Updating Helm Charts to use Dgraph 24.0.4

---

charts/dgraph/templates/alpha/statefulset.yaml

Gives opportunity to refer to the chart internals if needed, .e.g. using the following input
```yaml
alpha:
initContainers:
init:
enabled: true
env:
- name: "RELEASE_NAME"
value: "{{ .Release.Name }}"
- name: "ZERO_SVC"
value: "{{ template \"dgraph.zero.fullname\" . }}"
```
produces the output of
```yaml
initContainers:
- name: release-name-dgraph-alpha-init
image: docker.io/dgraph/dgraph:v23.0.1
imagePullPolicy: "IfNotPresent"
env:
- name: RELEASE_NAME
value: 'release-name'
- name: ZERO_SVC
value: 'release-name-dgraph-zero'
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/charts/110)

feat: allow tpl func in env for alpha init container

---

charts/dgraph/README.md
charts/dgraph/templates/alpha/statefulset.yaml
charts/dgraph/templates/ratel/deployment.yaml
charts/dgraph/templates/zero/statefulset.yaml
charts/dgraph/values.yaml

Sometimes it's much easier to import environment variables from configmap(s) and/or secret(s) instead of duplicating every possible value.

feat: add envFrom support

---

charts/dgraph/README.md
charts/dgraph/templates/alpha/statefulset.yaml
charts/dgraph/values.yaml

feat: add resources configuration for alpha init container

---

charts/dgraph/templates/_helpers.tpl
charts/dgraph/templates/serviceaccount.yaml

Currently, service name should be hardcoded to be properly rendered. This PR fixes such behavior according to the [comment](https://github.com/dgraph-io/charts/blob/master/charts/dgraph/values.yaml#L36-L37) in the values.

fix: service account name formula

---

charts/dgraph/templates/backups/cronjob-full.yaml
charts/dgraph/templates/backups/cronjob-inc.yaml

Installing the current helm chart Dgraph v24.0.5 failed if backup is enabled (using current Kubernetes v1.31):
`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "dgraph-cluster-1-dgraph-backups-inc" namespace: "prod" from "": no matches for kind "CronJob" in version "batch/v1beta1"
ensure CRDs are installed first`
The batch/v1beta1 API version of CronJob is no longer served as of v1.25.
[deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125)
Thanks

CronJob API version upgrade to batch/v1
